<?php

require_once("../core/Model.php");

class ExampleModel implements Model{
	function __construct($data = null){
		//TODO: db access and computation here
	}

	function test(){
		return "This is a message generated by the example model!";
	}
}

?>